"""Research corpus exploration API routes.

Provides semantic search and navigation across the Notion "Connaissance du terrain"
corpus (interviews, observations, themes, hypotheses, conclusions).

Embeddings are stored in data/notion_research.db (generated by scripts/embed_notion_research.py).
Query encoding uses DeepInfra's hosted Qwen3-Embedding-0.6B model.
"""

import json
import logging
import sqlite3
import threading

import numpy as np
import requests
from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse

from .. import config

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/research")

DEEPINFRA_URL = "https://api.deepinfra.com/v1/openai/embeddings"
EMBEDDING_MODEL = "Qwen/Qwen3-Embedding-0.6B"

# In-memory cache for embeddings (invalidated when DB file changes)
_cache_lock = threading.Lock()
_cache = {"chunks": None, "embeddings": None, "mtime": 0}

# Page metadata cache (avoids N+1 queries per search)
_page_cache_lock = threading.Lock()
_page_cache = {"pages": None, "mtime": 0}


def _get_db():
    """Get a read-only connection to the research database."""
    db_path = config.NOTION_RESEARCH_DB
    if not db_path.exists():
        return None
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def _blob_to_vec(blob):
    return np.frombuffer(blob, dtype=np.float32)


def _get_embeddings(conn):
    """Load and cache the normalized embeddings matrix."""
    db_path = config.NOTION_RESEARCH_DB
    mtime = db_path.stat().st_mtime

    with _cache_lock:
        if _cache["mtime"] == mtime and _cache["chunks"] is not None:
            return _cache["chunks"], _cache["embeddings"]

    rows = conn.execute(
        "SELECT id, page_id, chunk_index, text, database_key, embedding FROM chunks"
    ).fetchall()

    chunks = []
    vecs = []
    for row in rows:
        chunks.append({
            "id": row["id"],
            "page_id": row["page_id"],
            "chunk_index": row["chunk_index"],
            "text": row["text"],
            "database_key": row["database_key"],
        })
        vecs.append(_blob_to_vec(row["embedding"]))

    if vecs:
        embeddings = np.vstack(vecs)
        norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
        norms[norms == 0] = 1
        embeddings = embeddings / norms
    else:
        embeddings = np.empty((0, 0))

    with _cache_lock:
        _cache.update(chunks=chunks, embeddings=embeddings, mtime=mtime)

    return chunks, embeddings


def _get_pages(conn):
    """Load and cache page metadata (title, type, date, url, database)."""
    db_path = config.NOTION_RESEARCH_DB
    mtime = db_path.stat().st_mtime

    with _page_cache_lock:
        if _page_cache["mtime"] == mtime and _page_cache["pages"] is not None:
            return _page_cache["pages"]

    rows = conn.execute(
        "SELECT id, title, database_key, database_name, url, properties_json FROM pages"
    ).fetchall()

    pages = {}
    for row in rows:
        props = json.loads(row["properties_json"]) if row["properties_json"] else {}
        pages[row["id"]] = {
            "title": row["title"],
            "database_key": row["database_key"],
            "database_name": row["database_name"],
            "url": row["url"],
            "type": props.get("Type"),
            "date": props.get("Date"),
        }

    with _page_cache_lock:
        _page_cache.update(pages=pages, mtime=mtime)

    return pages


def _embed_query(text):
    """Encode a query string using DeepInfra API."""
    api_key = config.DEEPINFRA_API_KEY
    if not api_key:
        raise ValueError("DEEPINFRA_API_KEY not configured")

    resp = requests.post(
        DEEPINFRA_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": EMBEDDING_MODEL,
            "input": [text],
            "encoding_format": "float",
        },
        timeout=10,
    )
    resp.raise_for_status()
    data = resp.json()
    vec = np.array(data["data"][0]["embedding"], dtype=np.float32)
    vec = vec / np.linalg.norm(vec)
    return vec


def _cosine_scores(query_vec, embeddings):
    """Dot product against pre-normalized matrix."""
    return embeddings @ query_vec


def _extract_body(text):
    """Extract body text from a chunk, stripping the metadata header.

    Chunk format:
      Title
      [Database name]
      Key: Value
      ...
      ---           (only in multi-chunk pages)
      body text

    For single-chunk pages (no ---), the title line and metadata lines
    after it are stripped; any remaining content is the body.
    """
    if "\n---\n" in text:
        return text.split("\n---\n", 1)[1].strip()

    # No --- separator: skip title (line 0) + metadata lines
    lines = text.split("\n")
    body_start = 1  # skip title
    for i in range(1, len(lines)):
        stripped = lines[i].strip()
        if not stripped:
            body_start = i + 1
            continue
        if stripped.startswith("[") and stripped.endswith("]"):
            body_start = i + 1
            continue
        if ": " in stripped and len(stripped) < 200:
            body_start = i + 1
            continue
        # Non-metadata line found
        break
    body = "\n".join(lines[body_start:]).strip()
    return body


def _build_result(chunk, page_info, score=None):
    """Build a result dict from a chunk and its page metadata."""
    result = {
        "chunk_id": chunk["id"],
        "page_id": chunk["page_id"],
        "chunk_index": chunk["chunk_index"],
        "body": _extract_body(chunk["text"]),
        "database_key": chunk["database_key"],
        "page_title": page_info["title"] if page_info else None,
        "database_name": page_info["database_name"] if page_info else None,
        "page_url": page_info["url"] if page_info else None,
        "page_type": page_info["type"] if page_info else None,
        "page_date": page_info["date"] if page_info else None,
    }
    if score is not None:
        result["score"] = round(float(score), 4)
    return result


def _dedupe_by_page(results):
    """Keep only the best-scoring result per page_id."""
    seen = {}
    deduped = []
    for r in results:
        pid = r["page_id"]
        if pid not in seen:
            seen[pid] = len(deduped)
            r["matching_chunks"] = 1
            deduped.append(r)
        else:
            deduped[seen[pid]]["matching_chunks"] += 1
    return deduped


# ---------------------------------------------------------------------------
# Public helpers (used by HTML routes too)
# ---------------------------------------------------------------------------


def get_corpus_stats():
    """Return corpus stats dict, or None if DB not available."""
    conn = _get_db()
    if not conn:
        return None
    try:
        pages_n = conn.execute("SELECT COUNT(*) as n FROM pages").fetchone()["n"]
        chunks_n = conn.execute("SELECT COUNT(*) as n FROM chunks").fetchone()["n"]

        db_stats = conn.execute(
            "SELECT database_key, database_name, COUNT(*) as n "
            "FROM pages GROUP BY database_key"
        ).fetchall()

        chunk_counts = conn.execute(
            "SELECT database_key, COUNT(*) as n FROM chunks GROUP BY database_key"
        ).fetchall()
        chunks_by_db = {r["database_key"]: r["n"] for r in chunk_counts}

        type_rows = conn.execute(
            "SELECT properties_json FROM pages WHERE database_key = 'entretiens'"
        ).fetchall()
        type_counts = {}
        for row in type_rows:
            props = json.loads(row["properties_json"]) if row["properties_json"] else {}
            t = props.get("Type")
            if t:
                type_counts[t] = type_counts.get(t, 0) + 1

        return {
            "pages": pages_n,
            "chunks": chunks_n,
            "databases": [
                {
                    "key": r["database_key"],
                    "name": r["database_name"],
                    "pages": r["n"],
                    "chunks": chunks_by_db.get(r["database_key"], 0),
                }
                for r in db_stats
            ],
            "types": type_counts,
        }
    finally:
        conn.close()


def search_corpus(q, limit=20, db_filter=None, type_filter=None):
    """Run semantic search. Returns (results, total_chunks) or (None, None)."""
    conn = _get_db()
    if not conn:
        return None, None
    try:
        query_vec = _embed_query(q)
        chunks, embeddings = _get_embeddings(conn)
        pages = _get_pages(conn)
        if len(chunks) == 0:
            return [], len(chunks)

        scores = _cosine_scores(query_vec, embeddings)
        top_indices = np.argsort(scores)[::-1]

        raw_results = []
        for idx in top_indices:
            if len(raw_results) >= limit * 3:
                break
            chunk = chunks[idx]
            if db_filter and chunk["database_key"] not in db_filter:
                continue
            page_info = pages.get(chunk["page_id"])
            if type_filter and (not page_info or page_info.get("type") not in type_filter):
                continue
            raw_results.append(_build_result(chunk, page_info, scores[idx]))

        return _dedupe_by_page(raw_results)[:limit], len(chunks)
    finally:
        conn.close()


def find_similar_pages(chunk_id, limit=15):
    """Find pages similar to a given chunk. Returns (results, source_page_id) or (None, None)."""
    conn = _get_db()
    if not conn:
        return None, None
    try:
        chunks, embeddings = _get_embeddings(conn)
        pages = _get_pages(conn)

        target_idx = None
        for i, c in enumerate(chunks):
            if c["id"] == chunk_id:
                target_idx = i
                break
        if target_idx is None:
            return None, None

        source_page_id = chunks[target_idx]["page_id"]
        target_vec = embeddings[target_idx]
        scores = _cosine_scores(target_vec, embeddings)
        top_indices = np.argsort(scores)[::-1]

        raw_results = []
        for idx in top_indices:
            if len(raw_results) >= limit * 3:
                break
            if chunks[idx]["page_id"] == source_page_id:
                continue
            chunk = chunks[idx]
            page_info = pages.get(chunk["page_id"])
            raw_results.append(_build_result(chunk, page_info, scores[idx]))

        return _dedupe_by_page(raw_results)[:limit], source_page_id
    finally:
        conn.close()


def get_page(page_id):
    """Get full page details. Returns dict or None."""
    conn = _get_db()
    if not conn:
        return None
    try:
        page = conn.execute("SELECT * FROM pages WHERE id = ?", (page_id,)).fetchone()
        if not page:
            return None

        props = json.loads(page["properties_json"]) if page["properties_json"] else {}

        blocks = conn.execute(
            "SELECT type, text_content, position FROM blocks "
            "WHERE page_id = ? ORDER BY position",
            (page_id,),
        ).fetchall()

        relations = {}
        rels = conn.execute(
            "SELECT r.property_name, p.title, p.id as target_id "
            "FROM relations r "
            "LEFT JOIN pages p ON p.id = r.target_page_id "
            "WHERE r.source_page_id = ?",
            (page_id,),
        ).fetchall()
        for r in rels:
            prop = r["property_name"]
            if prop not in relations:
                relations[prop] = []
            relations[prop].append({"title": r["title"], "page_id": r["target_id"]})

        chunks = conn.execute(
            "SELECT id, chunk_index FROM chunks "
            "WHERE page_id = ? ORDER BY chunk_index",
            (page_id,),
        ).fetchall()

        return {
            "id": page["id"],
            "title": page["title"],
            "database_key": page["database_key"],
            "database_name": page["database_name"],
            "url": page["url"],
            "type": props.get("Type"),
            "date": props.get("Date"),
            "properties": props,
            "blocks": [
                {"type": b["type"], "text": b["text_content"], "position": b["position"]}
                for b in blocks
            ],
            "relations": relations,
            "chunk_ids": [c["id"] for c in chunks],
        }
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# API Routes
# ---------------------------------------------------------------------------


@router.get("/search")
def search(
    q: str = Query(default=""),
    limit: int = Query(default=20),
    db: list[str] = Query(default=[]),
    type: list[str] = Query(default=[]),
):
    """Semantic search across the research corpus.

    Query params:
        q: search query (required)
        limit: max results (default 20, max 50)
        db: database_key filter (repeatable)
        type: page Type filter (repeatable, e.g. "Verbatim", "Observation")
    """
    q = q.strip()
    if not q:
        return JSONResponse({"error": "Missing query parameter 'q'"}, status_code=400)

    limit = min(limit, 50)
    db_filter = set(db)
    type_filter = set(type)

    conn = _get_db()
    if not conn:
        return JSONResponse({"error": "Research database not found"}, status_code=404)

    try:
        query_vec = _embed_query(q)
        chunks, embeddings = _get_embeddings(conn)
        pages = _get_pages(conn)
        if len(chunks) == 0:
            return {"results": [], "query": q}

        scores = _cosine_scores(query_vec, embeddings)
        top_indices = np.argsort(scores)[::-1]

        # Collect more than needed before dedup
        raw_results = []
        for idx in top_indices:
            if len(raw_results) >= limit * 3:
                break
            chunk = chunks[idx]
            if db_filter and chunk["database_key"] not in db_filter:
                continue
            page_info = pages.get(chunk["page_id"])
            if type_filter and (not page_info or page_info.get("type") not in type_filter):
                continue
            raw_results.append(_build_result(chunk, page_info, scores[idx]))

        results = _dedupe_by_page(raw_results)[:limit]

        return {
            "results": results,
            "query": q,
            "total_chunks": len(chunks),
        }
    finally:
        conn.close()


@router.get("/similar/{chunk_id}")
def similar(chunk_id: int, limit: int = Query(default=15)):
    """Find chunks similar to a given chunk (deduplicated by page)."""
    limit = min(limit, 30)

    conn = _get_db()
    if not conn:
        return JSONResponse({"error": "Research database not found"}, status_code=404)

    try:
        chunks, embeddings = _get_embeddings(conn)
        pages = _get_pages(conn)

        target_idx = None
        for i, c in enumerate(chunks):
            if c["id"] == chunk_id:
                target_idx = i
                break
        if target_idx is None:
            return JSONResponse({"error": "Chunk not found"}, status_code=404)

        source_page_id = chunks[target_idx]["page_id"]
        target_vec = embeddings[target_idx]
        scores = _cosine_scores(target_vec, embeddings)
        top_indices = np.argsort(scores)[::-1]

        raw_results = []
        for idx in top_indices:
            if len(raw_results) >= limit * 3:
                break
            # Skip chunks from the source page
            if chunks[idx]["page_id"] == source_page_id:
                continue
            chunk = chunks[idx]
            page_info = pages.get(chunk["page_id"])
            raw_results.append(_build_result(chunk, page_info, scores[idx]))

        results = _dedupe_by_page(raw_results)[:limit]

        return {
            "results": results,
            "source_chunk_id": chunk_id,
            "source_page_id": source_page_id,
        }
    finally:
        conn.close()


@router.get("/pages/{page_id}")
def page_detail(page_id: str):
    """Full page details: properties, blocks, relations, chunks."""
    conn = _get_db()
    if not conn:
        return JSONResponse({"error": "Research database not found"}, status_code=404)

    try:
        page = conn.execute(
            "SELECT * FROM pages WHERE id = ?", (page_id,)
        ).fetchone()
        if not page:
            return JSONResponse({"error": "Page not found"}, status_code=404)

        props = json.loads(page["properties_json"]) if page["properties_json"] else {}

        blocks = conn.execute(
            "SELECT type, text_content, position FROM blocks "
            "WHERE page_id = ? ORDER BY position",
            (page_id,),
        ).fetchall()

        # Resolved relations
        relations = {}
        rels = conn.execute(
            "SELECT r.property_name, p.title, p.id as target_id "
            "FROM relations r "
            "LEFT JOIN pages p ON p.id = r.target_page_id "
            "WHERE r.source_page_id = ?",
            (page_id,),
        ).fetchall()
        for r in rels:
            prop = r["property_name"]
            if prop not in relations:
                relations[prop] = []
            relations[prop].append({
                "title": r["title"],
                "page_id": r["target_id"],
            })

        chunks = conn.execute(
            "SELECT id, chunk_index FROM chunks "
            "WHERE page_id = ? ORDER BY chunk_index",
            (page_id,),
        ).fetchall()

        return {
            "id": page["id"],
            "title": page["title"],
            "database_key": page["database_key"],
            "database_name": page["database_name"],
            "url": page["url"],
            "type": props.get("Type"),
            "date": props.get("Date"),
            "properties": props,
            "blocks": [
                {"type": b["type"], "text": b["text_content"], "position": b["position"]}
                for b in blocks
            ],
            "relations": relations,
            "chunk_ids": [c["id"] for c in chunks],
        }
    finally:
        conn.close()


@router.get("/stats")
def stats():
    """Corpus statistics, including type breakdown for entretiens."""
    conn = _get_db()
    if not conn:
        return JSONResponse({"error": "Research database not found"}, status_code=404)

    try:
        pages_n = conn.execute("SELECT COUNT(*) as n FROM pages").fetchone()["n"]
        blocks_n = conn.execute("SELECT COUNT(*) as n FROM blocks").fetchone()["n"]
        chunks_n = conn.execute("SELECT COUNT(*) as n FROM chunks").fetchone()["n"]

        db_stats = conn.execute(
            "SELECT database_key, database_name, COUNT(*) as n "
            "FROM pages GROUP BY database_key"
        ).fetchall()

        chunk_counts = conn.execute(
            "SELECT database_key, COUNT(*) as n FROM chunks GROUP BY database_key"
        ).fetchall()
        chunks_by_db = {r["database_key"]: r["n"] for r in chunk_counts}

        # Type breakdown for entretiens
        type_rows = conn.execute(
            "SELECT properties_json FROM pages WHERE database_key = 'entretiens'"
        ).fetchall()
        type_counts = {}
        for row in type_rows:
            props = json.loads(row["properties_json"]) if row["properties_json"] else {}
            t = props.get("Type")
            if t:
                type_counts[t] = type_counts.get(t, 0) + 1

        meta = {}
        for row in conn.execute("SELECT key, value FROM sync_meta").fetchall():
            meta[row["key"]] = row["value"]

        return {
            "pages": pages_n,
            "blocks": blocks_n,
            "chunks": chunks_n,
            "databases": [
                {
                    "key": r["database_key"],
                    "name": r["database_name"],
                    "pages": r["n"],
                    "chunks": chunks_by_db.get(r["database_key"], 0),
                }
                for r in db_stats
            ],
            "types": type_counts,
            "sync_meta": meta,
        }
    finally:
        conn.close()
