"""dashboard_publications

Revision ID: 87e9b1ca66b8
Revises: c4d72e1f9a8b
Create Date: 2026-05-29 12:15:30.690672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87e9b1ca66b8'
down_revision: Union[str, Sequence[str], None] = 'c4d72e1f9a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dashboard_slug', sa.Text(), nullable=False),
    sa.Column('publication_id', sa.Text(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('published_by', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_slug'], ['dashboards.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dashboard_publications_slug', 'dashboard_publications', ['dashboard_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cli_message_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), server_default=sa.text("'turn'::text"), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('backend', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('service_tier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('input_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_creation_5m_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_creation_1h_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_read_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('web_search_requests', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('web_fetch_requests', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('usage_events_conversation_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('usage_events_pkey'))
    )
    op.drop_index('idx_dashboard_publications_slug', table_name='dashboard_publications')
    op.drop_table('dashboard_publications')
    # ### end Alembic commands ###
