"""dashboard_publications

Revision ID: 87e9b1ca66b8
Revises: c4d72e1f9a8b
Create Date: 2026-05-29 12:15:30.690672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '87e9b1ca66b8'
down_revision: Union[str, Sequence[str], None] = 'c4d72e1f9a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dashboard_slug', sa.Text(), nullable=False),
    sa.Column('publication_id', sa.Text(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('published_by', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_slug'], ['dashboards.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dashboard_publications_slug', 'dashboard_publications', ['dashboard_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_dashboard_publications_slug', table_name='dashboard_publications')
    op.drop_table('dashboard_publications')
