"""enforce not null on default-backed columns

Revision ID: b12cbac64ff9
Revises: c89f7601677b
Create Date: 2026-06-17 09:00:14.261238

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b12cbac64ff9"
down_revision: Union[str, Sequence[str], None] = "c89f7601677b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Why: les colonnes n'avaient qu'un default Python (pas server_default), donc des lignes pré-existantes
    # peuvent contenir NULL ; on les remplit avant SET NOT NULL sinon la migration échoue en prod.
    op.execute("UPDATE matomo_dimensions SET active = true WHERE active IS NULL")
    op.execute("UPDATE matomo_events SET event_count = 0 WHERE event_count IS NULL")
    op.execute("UPDATE matomo_events SET visit_count = 0 WHERE visit_count IS NULL")
    op.execute("UPDATE reports SET version = 1 WHERE version IS NULL")
    op.execute("UPDATE reports SET archived = 0 WHERE archived IS NULL")
    op.execute("UPDATE uploaded_files SET is_text = false WHERE is_text IS NULL")
    op.execute("UPDATE uploaded_files SET av_scanned = false WHERE av_scanned IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matomo_dimensions",
        "active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "matomo_events", "event_count", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("0")
    )
    op.alter_column(
        "matomo_events", "visit_count", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("0")
    )
    op.alter_column(
        "reports", "version", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("1")
    )
    op.alter_column(
        "reports", "archived", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("0")
    )
    op.alter_column(
        "uploaded_files",
        "is_text",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "uploaded_files",
        "av_scanned",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "uploaded_files",
        "av_scanned",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "uploaded_files", "is_text", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("false")
    )
    op.alter_column(
        "reports", "archived", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("0")
    )
    op.alter_column(
        "reports", "version", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("1")
    )
    op.alter_column(
        "matomo_events", "visit_count", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("0")
    )
    op.alter_column(
        "matomo_events", "event_count", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("0")
    )
    op.alter_column(
        "matomo_dimensions",
        "active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###
